# Generated by Django 3.1.1 on 2020-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='employees',
            name='Is_Email_verified',
            field=models.BooleanField(default='False'),
        ),
    ]
