# Generated by Django 3.1.1 on 2020-09-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200926_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='name1',
            new_name='name',
        ),
    ]
