# Generated by Django 3.1.1 on 2020-09-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200926_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Is_Email_verified',
        ),
    ]
