# Generated by Django 3.1.3 on 2021-01-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp_data',
            new_name='price_data',
        ),
    ]
